### ISSUE TITLE
Error : EOF

### ISSUE THREAD

**Issue by farhad-arjmand** [mmcdole/gofeed#54] opened 2016-07-09 07:25 UTC
many times i have ERROR: EOF
for eample :http://basijnews.ir/fa/rss/39: EOF

**Comment by mmcdole** [comment] 2016-07-09 19:57
This feed parsed fine for me:

```go
package main

import (
	"fmt"

	"github.com/mmcdole/gofeed"
)

func main() {

	url := "http://basijnews.ir/fa/rss/39"
	parser := gofeed.NewParser()
	feed, err := parser.ParseURL(url)
	if err != nil {
		panic("Failed fetch and parse the feed!")
	}

	for _, item := range feed.Items {
		fmt.Println(item.Title)
	}

}
```

Can you post code where it does not?

**Comment by mmcdole** [comment] 2016-07-21 13:24
@farhad-arjmand can you please post an example code sample that exhibits the problem?

**Comment by mmcdole** [comment] 2016-08-22 13:34
Closing this issue for now as I have no steps to reproduce and I'm unable to reproduce it on my own.

**Closed by mmcdole** 2016-08-22 13:34 UTC
